In [14]:
import numpy as np
list_ = [ '1' , '2' , '3' ,'4'  , '5' ]
array_list = np.array(object = list_)

In [15]:
list_

['1', '2', '3', '4', '5']

In [16]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

 Q1. ans.)
yes there is an difference btw the data type of the variables list+ and array_list

In [26]:
type(list_)

list

In [27]:
type(array_list)

numpy.ndarray

In [24]:
list(list_)

['1', '2', '3', '4', '5']

In [25]:
list(array_list)

['1', '2', '3', '4', '5']

Q2.  ans

In [28]:
type(list(list_))

list

In [39]:
type(list(array_list))

list

Q3. ans

In [30]:
array_list = np.array(object = list_, dtype = int)

In [31]:
array_list

array([1, 2, 3, 4, 5])

In [37]:
type((array_list))

numpy.ndarray

Q4. ans

In [40]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [41]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [42]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
#num_array shape and size

In [44]:
np.shape(num_array)

(2, 3)

In [45]:
np.size(num_array)

6

Q5. ans

In [55]:
matrix = np.zeros((3,3))

In [56]:
matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. ans

In [58]:
matrix2 = np.eye((5))

In [59]:
matrix2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])